# Generated by Django 3.2.7 on 2021-09-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keepnotes',
            name='note',
            field=models.TextField(max_length=500),
        ),
    ]
