# Generated by Django 3.2.7 on 2021-09-20 14:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0002_alter_keepnotes_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keepnotes',
            name='id',
            field=models.UUIDField(default=uuid.UUID('181ffe68-1249-4107-a6b1-e53f7131a61a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
