# Generated by Django 3.2.7 on 2021-09-20 14:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0003_alter_keepnotes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keepnotes',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a0f27182-6adb-45c2-bcd0-e3705ce81a36'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
