# Generated by Django 3.2.7 on 2021-09-20 14:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0004_alter_keepnotes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keepnotes',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
