# Generated by Django 3.2.7 on 2021-09-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0006_keepnotes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keepnotes',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
