# Generated by Django 3.2.7 on 2021-09-22 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0012_alter_keepnotes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='keepnotes',
            name='time2',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
